# -*- coding: utf-8 -*-
"""Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LFq3VI4YXghmy6e1CxxbrGwLKBKeWM9X
"""

# Mount Google Drive to save model permanently
from google.colab import drive
drive.mount('/content/drive')



import torch
print(f"GPU Available: {torch.cuda.is_available()}")
print(f"GPU Name: {torch.cuda.get_device_name(0)}")
print(f"GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, TaskType
print("All libraries imported successfully! ✅")

from huggingface_hub import login
# login("YOUR_HF_TOKEN_HERE")  # Add your token locally
login()  # Token will be read from environment variable

from datasets import load_dataset

dataset = load_dataset("stanfordnlp/imdb")

print(dataset)
print(f"\nTrain size: {len(dataset['train'])}")
print(f"Test size: {len(dataset['test'])}")
print(f"\nSample:")
print(dataset['train'][0])

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)
print(f"Model loaded: {model_name} ✅")

def tokenize_function(examples):
    return tokenizer(
        examples['text'],
        padding='max_length',
        truncation=True,
        max_length=512
    )

print("Tokenizing dataset...")
tokenized_dataset = dataset.map(tokenize_function, batched=True)

print("Tokenization done! ✅")
print(tokenized_dataset)

!pip install torchao --upgrade -q

import importlib
import peft
importlib.reload(peft)

from peft import LoraConfig, get_peft_model, TaskType

# LoRA Configuration
lora_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r=16,
    lora_alpha=32,
    lora_dropout=0.1,
    target_modules=["q_lin", "v_lin"]
)

# Apply LoRA to model
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

from transformers import TrainingArguments, Trainer
import numpy as np

# Training arguments
training_args = TrainingArguments(
    output_dir="./sentiment-model",
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=100,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    report_to="none"
)

# Accuracy metric
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    accuracy = (predictions == labels).mean()
    return {"accuracy": accuracy}

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset['train'],
    eval_dataset=tokenized_dataset['test'],
    compute_metrics=compute_metrics
)

print("Starting training... ⏳")
trainer.train()

# Save to Google Drive permanently
model.save_pretrained("/content/drive/MyDrive/sentiment-lora-model")
tokenizer.save_pretrained("/content/drive/MyDrive/sentiment-lora-model")
print("Model saved to Google Drive! ✅")

from transformers import pipeline

# Load saved model for inference
classifier = pipeline(
    "text-classification",
    model=model,
    tokenizer=tokenizer,
    device=0  # GPU
)

# Test with custom reviews
test_reviews = [
    "This movie was absolutely amazing! Best film I've seen in years.",
    "Terrible movie, complete waste of time. I hated every minute.",
    "The acting was decent but the plot was very confusing.",
    "Outstanding performance by the lead actor. Highly recommended!",
    "Boring and predictable. Fell asleep halfway through."
]

for review in test_reviews:
    result = classifier(review)[0]
    label = "POSITIVE 😊" if result['label'] == 'LABEL_1' else "NEGATIVE 😞"
    print(f"Review: {review[:50]}...")
    print(f"Prediction: {label} (confidence: {result['score']:.2%})\n")

import gradio as gr
import torch
import numpy as np

def predict_sentiment(text):
    if not text.strip():
        return "⚠️ Please enter a movie review!", "", "", ""

    result = classifier(text, truncation=True, max_length=512)[0]
    label = result['label']
    score = result['score']

    if label == 'LABEL_1':
        sentiment = "POSITIVE"
        emoji = "😊"
        color_class = "positive"
    else:
        sentiment = "NEGATIVE"
        emoji = "😞"
        color_class = "negative"

    # Confidence bar
    confidence_pct = f"{score:.2%}"

    # Word count
    word_count = len(text.split())

    # Detailed analysis
    if score > 0.95:
        confidence_level = "Very High Confidence"
    elif score > 0.85:
        confidence_level = "High Confidence"
    elif score > 0.70:
        confidence_level = "Moderate Confidence"
    else:
        confidence_level = "Low Confidence"

    result_text = f"{emoji} {sentiment}"
    confidence_text = f"{confidence_pct} — {confidence_level}"
    stats_text = f"📝 Word Count: {word_count} | 🤖 Model: DistilBERT + LoRA | 🎯 Trained on: IMDb 50K"

    if sentiment == "POSITIVE":
        analysis = f"✅ This review expresses a POSITIVE sentiment towards the movie. The model is {confidence_pct} confident in this prediction."
    else:
        analysis = f"❌ This review expresses a NEGATIVE sentiment towards the movie. The model is {confidence_pct} confident in this prediction."

    return result_text, confidence_text, stats_text, analysis

# Custom CSS
css = """
.gradio-container {
    background: linear-gradient(135deg, #0a0e1a 0%, #1a1f35 100%) !important;
    font-family: 'Inter', sans-serif !important;
}

.main-title {
    text-align: center;
    background: linear-gradient(90deg, #00aaff, #00ff88);
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    font-size: 2.5rem !important;
    font-weight: 800 !important;
    margin-bottom: 0 !important;
}

.subtitle {
    text-align: center;
    color: #8b949e !important;
    font-size: 1rem !important;
    margin-top: 0 !important;
}

.label-container, .input-container {
    background: #0d1117 !important;
    border: 1px solid #1e2d3d !important;
    border-radius: 12px !important;
}

textarea {
    background: #0d1117 !important;
    color: #ffffff !important;
    border: 1px solid #1e2d3d !important;
    border-radius: 8px !important;
    font-size: 14px !important;
}

.gr-button-primary {
    background: linear-gradient(90deg, #00aaff, #00ff88) !important;
    border: none !important;
    border-radius: 8px !important;
    font-weight: 700 !important;
    color: #000 !important;
    padding: 12px 30px !important;
}

.gr-button-secondary {
    background: #1e2d3d !important;
    border: 1px solid #00aaff !important;
    border-radius: 8px !important;
    color: #00aaff !important;
}

footer { display: none !important; }
"""

# Build Interface
with gr.Blocks(css=css, theme=gr.themes.Base()) as demo:

    gr.HTML("""
        <div style='text-align:center; padding: 20px 0;'>
            <h1 style='background: linear-gradient(90deg, #00aaff, #00ff88);
                       -webkit-background-clip: text; -webkit-text-fill-color: transparent;
                       font-size: 2.5rem; font-weight: 800; margin: 0;'>
                🎬 SentimentLLM Pro
            </h1>
            <p style='color: #8b949e; font-size: 1rem; margin-top: 8px;'>
                Enterprise-Grade Sentiment Analysis | DistilBERT + LoRA | Fine-tuned on IMDb 50K
            </p>
            <div style='display: flex; justify-content: center; gap: 20px; margin-top: 15px;'>
                <span style='background: #0d1117; border: 1px solid #00aaff44;
                             border-radius: 20px; padding: 5px 15px; color: #00aaff; font-size: 12px;'>
                    ⚡ 91.5% Accuracy
                </span>
                <span style='background: #0d1117; border: 1px solid #00ff8844;
                             border-radius: 20px; padding: 5px 15px; color: #00ff88; font-size: 12px;'>
                    🧠 LoRA Fine-tuned
                </span>
                <span style='background: #0d1117; border: 1px solid #ff660044;
                             border-radius: 20px; padding: 5px 15px; color: #ff6600; font-size: 12px;'>
                    🎯 50K Training Samples
                </span>
            </div>
        </div>
    """)

    gr.HTML("<hr style='border-color: #1e2d3d; margin: 10px 0;'>")

    with gr.Row():
        with gr.Column(scale=1):
            gr.HTML("<h3 style='color: #ffffff;'>📝 Input</h3>")
            text_input = gr.Textbox(
                lines=8,
                placeholder="Enter your movie review here...\n\nExample: 'This film was an absolute masterpiece. The director's vision was stunning and the performances were incredible...'",
                label="Movie Review"
            )

            with gr.Row():
                submit_btn = gr.Button("🔍 Analyze Sentiment", variant="primary")
                clear_btn = gr.Button("🗑️ Clear", variant="secondary")

            gr.HTML("<h3 style='color: #ffffff; margin-top: 20px;'>💡 Try These Examples</h3>")
            gr.Examples(
                examples=[
                    ["This movie was an absolute masterpiece. The storytelling was brilliant, acting superb, and cinematography breathtaking. One of the best films of the decade!"],
                    ["Complete disaster of a film. Poor acting, nonsensical plot, and terrible special effects. I walked out after 30 minutes. Total waste of money."],
                    ["A decent film with some good moments but ultimately falls short of expectations. The first half was engaging but it lost momentum towards the end."],
                    ["Absolutely phenomenal! Every scene was crafted with such care and attention to detail. The lead performance deserves every award possible."],
                    ["Dreadful experience. The script was poorly written, the pacing was off, and the characters were completely unlikeable. Avoid at all costs."]
                ],
                inputs=text_input
            )

        with gr.Column(scale=1):
            gr.HTML("<h3 style='color: #ffffff;'>📊 Analysis Results</h3>")

            sentiment_output = gr.Textbox(
                label="🎯 Sentiment",
                lines=1
            )
            confidence_output = gr.Textbox(
                label="📈 Confidence Score",
                lines=1
            )
            analysis_output = gr.Textbox(
                label="🔍 Detailed Analysis",
                lines=3
            )
            stats_output = gr.Textbox(
                label="ℹ️ Model Info",
                lines=1
            )

    gr.HTML("<hr style='border-color: #1e2d3d; margin: 20px 0;'>")

    gr.HTML("""
        <div style='text-align: center; color: #8b949e; font-size: 12px; padding: 10px;'>
            Built with DistilBERT + LoRA (PEFT) | Fine-tuned on Stanford IMDb Dataset |
            Ayushman Mishra | VIT Bhopal University
        </div>
    """)

    submit_btn.click(
        fn=predict_sentiment,
        inputs=text_input,
        outputs=[sentiment_output, confidence_output, stats_output, analysis_output]
    )

    clear_btn.click(
        fn=lambda: ("", "", "", ""),
        outputs=[sentiment_output, confidence_output, stats_output, analysis_output]
    )

demo.launch(share=True)

!pip install huggingface_hub -q

from huggingface_hub import HfApi
api = HfApi()

# Push model to HuggingFace Hub
model.push_to_hub("tekvora7/sentimentllm-distilbert-lora")
tokenizer.push_to_hub("tekvora7/sentimentllm-distilbert-lora")

print("Model pushed to HuggingFace Hub! ✅")

from huggingface_hub import login
# login("YOUR_HF_TOKEN_HERE")  # Add your token locally
login()

model.push_to_hub("tekvora7/sentimentllm-distilbert-lora")
tokenizer.push_to_hub("tekvora7/sentimentllm-distilbert-lora")
print("Model pushed! ✅")